<?php
/**
 * GetAddressInfoResponseUtxosTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetAddressInfoResponseUtxosTest Class Doc Comment
 *
 * @category    Class */
// * @description GetAddressInfoResponseUtxos
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetAddressInfoResponseUtxosTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetAddressInfoResponseUtxos"
     */
    public function testGetAddressInfoResponseUtxos()
    {
    }

    /**
     * Test attribute "index"
     */
    public function testPropertyIndex()
    {
    }

    /**
     * Test attribute "txid"
     */
    public function testPropertyTxid()
    {
    }

    /**
     * Test attribute "blockheight"
     */
    public function testPropertyBlockheight()
    {
    }

    /**
     * Test attribute "blocktime"
     */
    public function testPropertyBlocktime()
    {
    }

    /**
     * Test attribute "script_pub_key"
     */
    public function testPropertyScriptPubKey()
    {
    }

    /**
     * Test attribute "used"
     */
    public function testPropertyUsed()
    {
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
    }

    /**
     * Test attribute "tokens"
     */
    public function testPropertyTokens()
    {
    }
}
