<?php
/**
 * GetBlockResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetBlockResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description GetBlockResponse
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetBlockResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetBlockResponse"
     */
    public function testGetBlockResponse()
    {
    }

    /**
     * Test attribute "hash"
     */
    public function testPropertyHash()
    {
    }

    /**
     * Test attribute "confirmations"
     */
    public function testPropertyConfirmations()
    {
    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "merkleroot"
     */
    public function testPropertyMerkleroot()
    {
    }

    /**
     * Test attribute "tx"
     */
    public function testPropertyTx()
    {
    }

    /**
     * Test attribute "time"
     */
    public function testPropertyTime()
    {
    }

    /**
     * Test attribute "nonce"
     */
    public function testPropertyNonce()
    {
    }

    /**
     * Test attribute "bits"
     */
    public function testPropertyBits()
    {
    }

    /**
     * Test attribute "difficulty"
     */
    public function testPropertyDifficulty()
    {
    }

    /**
     * Test attribute "previousblockhash"
     */
    public function testPropertyPreviousblockhash()
    {
    }

    /**
     * Test attribute "nextblockhash"
     */
    public function testPropertyNextblockhash()
    {
    }

    /**
     * Test attribute "reward"
     */
    public function testPropertyReward()
    {
    }
}
