<?php
/**
 * GetTokenMetadataResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetTokenMetadataResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description GetTokenMetadataResponse
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetTokenMetadataResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetTokenMetadataResponse"
     */
    public function testGetTokenMetadataResponse()
    {
    }

    /**
     * Test attribute "token_id"
     */
    public function testPropertyTokenId()
    {
    }

    /**
     * Test attribute "divisibility"
     */
    public function testPropertyDivisibility()
    {
    }

    /**
     * Test attribute "lock_status"
     */
    public function testPropertyLockStatus()
    {
    }

    /**
     * Test attribute "aggregation_policy"
     */
    public function testPropertyAggregationPolicy()
    {
    }

    /**
     * Test attribute "total_supply"
     */
    public function testPropertyTotalSupply()
    {
    }

    /**
     * Test attribute "num_of_holders"
     */
    public function testPropertyNumOfHolders()
    {
    }

    /**
     * Test attribute "num_of_transfers"
     */
    public function testPropertyNumOfTransfers()
    {
    }

    /**
     * Test attribute "numof_issuance"
     */
    public function testPropertyNumofIssuance()
    {
    }

    /**
     * Test attribute "num_of_burns"
     */
    public function testPropertyNumOfBurns()
    {
    }

    /**
     * Test attribute "first_block"
     */
    public function testPropertyFirstBlock()
    {
    }

    /**
     * Test attribute "issuance_txid"
     */
    public function testPropertyIssuanceTxid()
    {
    }

    /**
     * Test attribute "issue_address"
     */
    public function testPropertyIssueAddress()
    {
    }

    /**
     * Test attribute "metadata_of_issuance"
     */
    public function testPropertyMetadataOfIssuance()
    {
    }

    /**
     * Test attribute "metadata_of_utxo"
     */
    public function testPropertyMetadataOfUtxo()
    {
    }
}
