<?php
/**
 * GetTokenMetadataResponseMetadataOfIssuanceDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetTokenMetadataResponseMetadataOfIssuanceDataTest Class Doc Comment
 *
 * @category    Class */
// * @description GetTokenMetadataResponseMetadataOfIssuanceData
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetTokenMetadataResponseMetadataOfIssuanceDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetTokenMetadataResponseMetadataOfIssuanceData"
     */
    public function testGetTokenMetadataResponseMetadataOfIssuanceData()
    {
    }

    /**
     * Test attribute "token_name"
     */
    public function testPropertyTokenName()
    {
    }

    /**
     * Test attribute "issuer"
     */
    public function testPropertyIssuer()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "user_data"
     */
    public function testPropertyUserData()
    {
    }
}
