<?php
/**
 * GetTransactionInfoResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetTransactionInfoResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description GetTransactionInfoResponse
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetTransactionInfoResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetTransactionInfoResponse"
     */
    public function testGetTransactionInfoResponse()
    {
    }

    /**
     * Test attribute "hex"
     */
    public function testPropertyHex()
    {
    }

    /**
     * Test attribute "txid"
     */
    public function testPropertyTxid()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "locktime"
     */
    public function testPropertyLocktime()
    {
    }

    /**
     * Test attribute "vin"
     */
    public function testPropertyVin()
    {
    }

    /**
     * Test attribute "vout"
     */
    public function testPropertyVout()
    {
    }

    /**
     * Test attribute "blocktime"
     */
    public function testPropertyBlocktime()
    {
    }

    /**
     * Test attribute "blockheight"
     */
    public function testPropertyBlockheight()
    {
    }

    /**
     * Test attribute "totalsent"
     */
    public function testPropertyTotalsent()
    {
    }

    /**
     * Test attribute "fee"
     */
    public function testPropertyFee()
    {
    }

    /**
     * Test attribute "blockhash"
     */
    public function testPropertyBlockhash()
    {
    }

    /**
     * Test attribute "time"
     */
    public function testPropertyTime()
    {
    }

    /**
     * Test attribute "confirmations"
     */
    public function testPropertyConfirmations()
    {
    }
}
