<?php
/**
 * GetTokenHoldersResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetTokenHoldersResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description GetTokenHoldersResponse
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetTokenHoldersResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetTokenHoldersResponse"
     */
    public function testGetTokenHoldersResponse()
    {
    }

    /**
     * Test attribute "token_id"
     */
    public function testPropertyTokenId()
    {
    }

    /**
     * Test attribute "holders"
     */
    public function testPropertyHolders()
    {
    }

    /**
     * Test attribute "divibility"
     */
    public function testPropertyDivibility()
    {
    }

    /**
     * Test attribute "lock_status"
     */
    public function testPropertyLockStatus()
    {
    }

    /**
     * Test attribute "aggregation_policy"
     */
    public function testPropertyAggregationPolicy()
    {
    }

    /**
     * Test attribute "some_utxo"
     */
    public function testPropertySomeUtxo()
    {
    }
}
