<?php
/**
 * InsightApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * InsightApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InsightApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getAddress
     *
     * Returns address object.
     *
     */
    public function testGetAddress()
    {
    }

    /**
     * Test case for getAddressBalance
     *
     * Returns address balance in sats.
     *
     */
    public function testGetAddressBalance()
    {
    }

    /**
     * Test case for getAddressTotalReceived
     *
     * Returns total received by address in sats.
     *
     */
    public function testGetAddressTotalReceived()
    {
    }

    /**
     * Test case for getAddressTotalSent
     *
     * Returns total sent by address in sats.
     *
     */
    public function testGetAddressTotalSent()
    {
    }

    /**
     * Test case for getAddressUnconfirmedBalance
     *
     * Returns address unconfirmed balance in sats.
     *
     */
    public function testGetAddressUnconfirmedBalance()
    {
    }

    /**
     * Test case for getAddressUtxos
     *
     * Returns all UTXOs at a given address.
     *
     */
    public function testGetAddressUtxos()
    {
    }

    /**
     * Test case for getBlock
     *
     * Returns information regarding a Neblio block.
     *
     */
    public function testGetBlock()
    {
    }

    /**
     * Test case for getBlockIndex
     *
     * Returns block hash of block.
     *
     */
    public function testGetBlockIndex()
    {
    }

    /**
     * Test case for getRawTx
     *
     * Returns raw transaction hex.
     *
     */
    public function testGetRawTx()
    {
    }

    /**
     * Test case for getStatus
     *
     * Utility API for calling several blockchain node functions.
     *
     */
    public function testGetStatus()
    {
    }

    /**
     * Test case for getSync
     *
     * Get node sync status.
     *
     */
    public function testGetSync()
    {
    }

    /**
     * Test case for getTx
     *
     * Returns transaction object.
     *
     */
    public function testGetTx()
    {
    }

    /**
     * Test case for getTxs
     *
     * Get transactions by block or address.
     *
     */
    public function testGetTxs()
    {
    }

    /**
     * Test case for sendTx
     *
     * Broadcasts a signed raw transaction to the network (not NTP1 specific).
     *
     */
    public function testSendTx()
    {
    }
}
